### ISSUE TITLE
Submit always jumps back to first non-annotated text

### ISSUE THREAD

**Issue by rubenaster** [timoklimmer/neanno#1]
Hi,
I'm currently working with the latest version and noticed the following issue:

When I annotate e.g. the first 2 texts within a set, skip a few texts and annotate some more texts, then the tool always jumps back to the first non-annotated text. I guess the old behavior was that the tool jumped to the next non-annotated text _after_ the current text that has been submitted.

Is the current behavior correct? Since skipping texts is often done intended.

**Comment by timoklimmer** [comment]
Thanks for bringing this up! The behaviour you describe is actually as expected. Reason is that when you do a "Submit/Go to next best" it should (and does) go to the next best text - which is currently considered the first text in the dataset that is not annotated yet. In future, this might change to a text where a model is still very uncertain. By that, we could improve training case efficiency.

Nevertheless if you **press Ctrl+Shift+Enter** instead of Ctrl+Enter it submits the text and jumps directly to the next text that follows the current text.

In case the shortcuts are not clear yet: there is a Shortcuts button on bottom. The dialog behind lists all shortcuts.
